/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as AiMatchRouteImport } from './routes/ai-match'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMatchResumeRouteImport } from './routes/api/match-resume'
import { Route as ApiPublicImportJobsRouteImport } from './routes/api/public/import-jobs'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMatchRoute = AiMatchRouteImport.update({
  id: '/ai-match',
  path: '/ai-match',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchResumeRoute = ApiMatchResumeRouteImport.update({
  id: '/api/match-resume',
  path: '/api/match-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImportJobsRoute = ApiPublicImportJobsRouteImport.update({
  id: '/api/public/import-jobs',
  path: '/api/public/import-jobs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-match': typeof AiMatchRoute
  '/candidates': typeof CandidatesRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/industries': typeof IndustriesRoute
  '/jobs': typeof JobsRoute
  '/services': typeof ServicesRoute
  '/api/match-resume': typeof ApiMatchResumeRoute
  '/api/public/import-jobs': typeof ApiPublicImportJobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-match': typeof AiMatchRoute
  '/candidates': typeof CandidatesRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/industries': typeof IndustriesRoute
  '/jobs': typeof JobsRoute
  '/services': typeof ServicesRoute
  '/api/match-resume': typeof ApiMatchResumeRoute
  '/api/public/import-jobs': typeof ApiPublicImportJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-match': typeof AiMatchRoute
  '/candidates': typeof CandidatesRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/industries': typeof IndustriesRoute
  '/jobs': typeof JobsRoute
  '/services': typeof ServicesRoute
  '/api/match-resume': typeof ApiMatchResumeRoute
  '/api/public/import-jobs': typeof ApiPublicImportJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-match'
    | '/candidates'
    | '/contact'
    | '/employers'
    | '/industries'
    | '/jobs'
    | '/services'
    | '/api/match-resume'
    | '/api/public/import-jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-match'
    | '/candidates'
    | '/contact'
    | '/employers'
    | '/industries'
    | '/jobs'
    | '/services'
    | '/api/match-resume'
    | '/api/public/import-jobs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-match'
    | '/candidates'
    | '/contact'
    | '/employers'
    | '/industries'
    | '/jobs'
    | '/services'
    | '/api/match-resume'
    | '/api/public/import-jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiMatchRoute: typeof AiMatchRoute
  CandidatesRoute: typeof CandidatesRoute
  ContactRoute: typeof ContactRoute
  EmployersRoute: typeof EmployersRoute
  IndustriesRoute: typeof IndustriesRoute
  JobsRoute: typeof JobsRoute
  ServicesRoute: typeof ServicesRoute
  ApiMatchResumeRoute: typeof ApiMatchResumeRoute
  ApiPublicImportJobsRoute: typeof ApiPublicImportJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-match': {
      id: '/ai-match'
      path: '/ai-match'
      fullPath: '/ai-match'
      preLoaderRoute: typeof AiMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/match-resume': {
      id: '/api/match-resume'
      path: '/api/match-resume'
      fullPath: '/api/match-resume'
      preLoaderRoute: typeof ApiMatchResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/import-jobs': {
      id: '/api/public/import-jobs'
      path: '/api/public/import-jobs'
      fullPath: '/api/public/import-jobs'
      preLoaderRoute: typeof ApiPublicImportJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiMatchRoute: AiMatchRoute,
  CandidatesRoute: CandidatesRoute,
  ContactRoute: ContactRoute,
  EmployersRoute: EmployersRoute,
  IndustriesRoute: IndustriesRoute,
  JobsRoute: JobsRoute,
  ServicesRoute: ServicesRoute,
  ApiMatchResumeRoute: ApiMatchResumeRoute,
  ApiPublicImportJobsRoute: ApiPublicImportJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
